#pragma once

// TRAP
#define UNIT_TRAP_GROUP_NONE        0
#define UNIT_TRAP_GROUP_RECOVERY    1
#define UNIT_TRAP_GROUP_DAMAGE      2
#define UNIT_TRAP_GROUP_FIRE        3
#define UNIT_TRAP_GROUP_ICE         4
#define UNIT_TRAP_GROUP_GATE        5
#define UNIT_TRAP_GROUP_END         6

#define UNIT_TRAP_ID_IGNORE         (-1)

// sub_id
#define UNIT_TRAP_GATE_ID_NONE       0
#define UNIT_TRAP_GATE_ID_GOAL       1
//#define UNIT_TRAP_GATE_ID_MAX       255

#define UNIT_TRAP_GATE_ID_GO_NEXT    (0x00001000)
#define UNIT_TRAP_GATE_ID_GO_NEXT_W  (UNIT_TRAP_GATE_ID_GO_NEXT | 0x00000100)
#define UNIT_TRAP_GATE_ID_GO_NEXT_N  (UNIT_TRAP_GATE_ID_GO_NEXT | 0x00000200)
#define UNIT_TRAP_GATE_ID_GO_NEXT_E  (UNIT_TRAP_GATE_ID_GO_NEXT | 0x00000400)
#define UNIT_TRAP_GATE_ID_GO_NEXT_S  (UNIT_TRAP_GATE_ID_GO_NEXT | 0x00000800)
